2025-05-23 13:39:29,462 INFO    MainThread:16724 [wandb_init.py:setup_run_log_directory():724] Logging user logs to c:\Users\eduar\MIA\1year_2semester\nlp\consumer-complaint-transformer-classifier\wandb\run-20250523_133929-2yikg0i7\logs\debug.log
2025-05-23 13:39:29,462 INFO    MainThread:16724 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to c:\Users\eduar\MIA\1year_2semester\nlp\consumer-complaint-transformer-classifier\wandb\run-20250523_133929-2yikg0i7\logs\debug-internal.log
2025-05-23 13:39:29,462 INFO    MainThread:16724 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002CE1445B0D0>
2025-05-23 13:39:29,463 INFO    MainThread:16724 [wandb_init.py:init():852] calling init triggers
2025-05-23 13:39:29,463 INFO    MainThread:16724 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'model': 'distilbert-base-uncased', 'learning_rate': 2e-05, 'batch_size': 16, 'epochs': 5, 'max_length': 512, 'iteration': 1, 'sample_size_per_class': 100, '_wandb': {}}
2025-05-23 13:39:32,346 INFO    MainThread:16724 [wandb_init.py:init():893] starting backend
2025-05-23 13:39:32,348 INFO    MainThread:16724 [wandb_init.py:init():897] sending inform_init request
2025-05-23 13:39:32,353 INFO    MainThread:16724 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-05-23 13:39:32,353 INFO    MainThread:16724 [wandb_init.py:init():907] backend started and connected
2025-05-23 13:39:32,358 INFO    MainThread:16724 [wandb_run.py:_label_probe_notebook():1376] probe notebook
2025-05-23 13:39:32,387 INFO    MainThread:16724 [wandb_run.py:_label_probe_notebook():1386] Unable to probe notebook: 'charmap' codec can't decode byte 0x81 in position 30541: character maps to <undefined>
2025-05-23 13:39:32,387 INFO    MainThread:16724 [wandb_init.py:init():1005] updated telemetry
2025-05-23 13:39:32,480 INFO    MainThread:16724 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-23 13:39:33,051 INFO    MainThread:16724 [wandb_init.py:init():1104] starting run threads in backend
2025-05-23 13:39:33,408 INFO    MainThread:16724 [wandb_run.py:_console_start():2573] atexit reg
2025-05-23 13:39:33,409 INFO    MainThread:16724 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-23 13:39:33,409 INFO    MainThread:16724 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-23 13:39:33,409 INFO    MainThread:16724 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-23 13:39:33,410 INFO    MainThread:16724 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-23 13:39:33,842 INFO    MainThread:16724 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-05-23 13:42:05,407 INFO    MainThread:16724 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-05-23 13:42:05,415 INFO    MainThread:16724 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-05-23 13:42:43,115 INFO    MainThread:16724 [wandb_run.py:_finish():2321] finishing run pt_cel/consumer-complaints-robustness/2yikg0i7
2025-05-23 13:42:43,120 INFO    MainThread:16724 [jupyter.py:save_history():477] not saving jupyter history
2025-05-23 13:42:43,120 INFO    MainThread:16724 [jupyter.py:save_ipynb():401] not saving jupyter notebook
2025-05-23 13:42:43,120 INFO    MainThread:16724 [wandb_init.py:_jupyter_teardown():628] cleaning up jupyter logic
2025-05-23 13:42:43,120 INFO    MainThread:16724 [wandb_run.py:_atexit_cleanup():2538] got exitcode: 0
2025-05-23 13:42:43,121 INFO    MainThread:16724 [wandb_run.py:_restore():2520] restore
2025-05-23 13:42:43,122 INFO    MainThread:16724 [wandb_run.py:_restore():2526] restore done
2025-05-23 13:42:45,413 INFO    MainThread:16724 [wandb_run.py:_footer_history_summary_info():4188] rendering history
2025-05-23 13:42:45,414 INFO    MainThread:16724 [wandb_run.py:_footer_history_summary_info():4220] rendering summary
2025-05-23 13:42:45,414 INFO    MainThread:16724 [wandb_run.py:_footer_sync_info():4149] logging synced files
