{"time":"2025-05-23T13:33:38.430096+01:00","level":"INFO","msg":"stream: starting","core version":"0.19.11","symlink path":"c:\\Users\\eduar\\MIA\\1year_2semester\\nlp\\consumer-complaint-transformer-classifier\\wandb\\run-20250523_133337-rqzugdw5\\logs\\debug-core.log"}
{"time":"2025-05-23T13:33:38.8312284+01:00","level":"INFO","msg":"created new stream","id":"rqzugdw5"}
{"time":"2025-05-23T13:33:38.8312284+01:00","level":"INFO","msg":"stream: started","id":"rqzugdw5"}
{"time":"2025-05-23T13:33:38.8312284+01:00","level":"INFO","msg":"handler: started","stream_id":"rqzugdw5"}
{"time":"2025-05-23T13:33:38.8312284+01:00","level":"INFO","msg":"writer: Do: started","stream_id":"rqzugdw5"}
{"time":"2025-05-23T13:33:38.8312284+01:00","level":"INFO","msg":"sender: started","stream_id":"rqzugdw5"}
{"time":"2025-05-23T13:33:39.1349397+01:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-05-23T13:35:00.2126179+01:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2025-05-23T13:35:45.9185586+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/pt_cel/consumer-complaints-robustness/rqzugdw5/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-23T13:35:46.2507424+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.3:54260->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-23T13:35:48.2000415+01:00","level":"INFO","msg":"Resuming system monitor"}
{"time":"2025-05-23T13:36:09.3041641+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/pt_cel/consumer-complaints-robustness/rqzugdw5/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-23T13:36:09.7278444+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-23T13:36:35.1262232+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-23T13:36:35.3168665+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/pt_cel/consumer-complaints-robustness/rqzugdw5/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-23T13:36:44.6137121+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/pt_cel/consumer-complaints-robustness/rqzugdw5/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-05-23T13:36:44.985568+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-05-23T13:37:01.1810209+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/pt_cel/consumer-complaints-robustness/rqzugdw5/file_stream\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-05-23T13:37:01.9974875+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp: lookup api.wandb.ai: no such host"}
{"time":"2025-05-23T13:37:08.5671842+01:00","level":"INFO","msg":"Pausing system monitor"}
{"time":"2025-05-23T13:38:16.8451728+01:00","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-05-23T13:38:16.847156+01:00","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-05-23T13:38:17.8620857+01:00","level":"INFO","msg":"handler: operation stats","stats":{}}
{"time":"2025-05-23T13:38:18.9417237+01:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 172.20.10.3:54579->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-05-23T13:38:22.8024261+01:00","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-05-23T13:38:23.2189535+01:00","level":"INFO","msg":"stream: closing","id":"rqzugdw5"}
{"time":"2025-05-23T13:38:23.2189535+01:00","level":"INFO","msg":"handler: closed","stream_id":"rqzugdw5"}
{"time":"2025-05-23T13:38:23.2199236+01:00","level":"INFO","msg":"writer: Close: closed","stream_id":"rqzugdw5"}
{"time":"2025-05-23T13:38:23.2199236+01:00","level":"INFO","msg":"sender: closed","stream_id":"rqzugdw5"}
{"time":"2025-05-23T13:38:23.2199236+01:00","level":"INFO","msg":"stream: closed","id":"rqzugdw5"}
